Controllers films users .
dmmitr632/java-filmorate pull request #11
Opened 2022-08-31 13:01 UTC by dmmitr632

2022-09-01 17:40 UTC, alexache requested changes
Работа хорошая, но есть комментарии

2022-09-01 17:40 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserValidationTest.java
> +//@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
В рамках данного спринта можно обойтись более простым тестом, где не поднимается спринг приложение, а просто создается инстанс UserController / FilmController и вызываются его методы

2022-09-01 17:40 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void addFilmWithEmptyName() {
Тест кейсов, пожалуй, должно быть больше - валидация разных полей и некорректных данных, поданных туда

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank @NotEmpty String name;
Несмотря на наличие аннотаций, они не заменяют (в данной комбинации) модификаторы доступа - private и т.д.

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping(value = "/films")
Зачем в данном случае писать value="/films" а не как в других маппингах без value?

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        LocalDate dateTime = LocalDate.of(1895, Month.DECEMBER, 28);
Можно хранить это константной (private static final LocalDate CINEMA_BIRTHDAY)

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().atStartOfDay(ZoneId.systemDefault()).toInstant()
А для чего эти .atStartOfDay()?

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Пожалуй лучше хранить не листом, а мапой, где ключ - это айди

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info(film.toString());
Не хватает пояснения в логе о том, что происходит

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film otherFilm : films) {
Не очень оптимально каждый раз обходить весь лист в поисках такого же айди, Если перейти на мапу, это будет не так медленно

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) {
Странное название метода, это ведь update? create - это чаще про создание чего-то нового

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                log.info(film.toString());
Тоже не хватает пояснения о выполняемой операции

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final List<User> users = new ArrayList<>();
Тут тоже мапа лучше подойдет

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info(user.toString());
Такой же комментарий про логгирование

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping(value = "/users")
Такой же комментарий про излишние использование value=

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            System.out.println("Wrong login");
Для чего System.out а не логгирование?

2022-09-01 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "blank email") @NotEmpty(message = "empty email") @Email(message = "wrong email") String email;
Такой же комментарий про пропущенные модификаторы доступа

2022-09-01 21:47 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().atStartOfDay(ZoneId.systemDefault()).toInstant()
film.getReleaseDate().toInstant() выдаст ошибку Cannot resolve method 'toInstant' in 'LocalDate'. См, например https://stackoverflow.com/questions/23215299/how-to-convert-a-localdate-to-an-instant
Можно еще поменять тип с LocalDate на Date, но он считается устаревшим.

2022-09-01 21:50 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film otherFilm : films) {
См. коммент про postman-тесты

2022-09-01 21:51 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) {
Да, забыл поменять

2022-09-01 21:54 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping(value = "/films")
У меня во всех маппингах путь указан же. Ты имеешь ввиду, что можно его  вынести в аннотацию наверх, @RequestMapping("films") перед FilmController?

2022-09-01 21:56 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final List<User> users = new ArrayList<>();
Я так сначала и сделал. Но тогда не проходится один из тестов postman, который смотрит размер json-а, он рассчитан на list, видимо. Пишет, что размер undefined, а нужно 1.

2022-09-01 21:58 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            System.out.println("Wrong login");
Мне так заметнее было в терминале :) Может, можно как-то цветом выделить?

2022-09-01 22:34 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Я осознал, что можно сделать лист из мапы конкретно для того get-запроса.

2022-09-02 00:34 UTC, dmmitr632 commented
Кажется, все исправил. Только не очень понятно, почему 
`return (List<Film>) films.values();`
вызывало ошибку в тестах postman, а 
`return new ArrayList<>(films.values());`
нет

2022-09-02 14:28 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping(value = "/films")
Я имею в виду писать @PutMapping("/films") вместо @PutMapping(value="/films")

2022-09-02 14:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            System.out.println("Wrong login");
Можно написать профиль для логгера (logback здесь по умолчанию, насколько помню, и делать любые цвета, какие хочется)

2022-09-02 14:38 UTC, alexache approved these changes
Комментарии исправлены

2022-09-02 14:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().atStartOfDay(ZoneId.systemDefault()).toInstant()
Почему не просто film.getReleaseDate().isBefore(CINEMA_BIRTHDAY) ?

2022-09-02 14:48 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().atStartOfDay(ZoneId.systemDefault()).toInstant()
Не знаю, затупил. Наверное, из 8го проекта скопировал, там время кроме даты сравнивалось.

2022-09-02 14:50 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping(value = "/films")
А, ну да. В общем, я наверх уже вынес.

2022-09-02 15:20 UTC, merged