Add friends likes
dmmitr632/java-filmorate pull request #15
Opened 2022-09-16 13:14 UTC by dmmitr632

2022-09-17 20:18 UTC, alexache requested changes

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Map<Integer, Film> getFilms();
Нехорошо выдавать внутренности хранения наружу

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    int generateId();
Зачем этот метод в интерфейсе?

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        log.info("Film by id {}, {}", filmId, this.getFilms().get(filmId));
Зачем два раза вызывать this.getFilms().get(filmId)?

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if ((!userStorage.getUsers().containsKey(user1Id)) || (!userStorage.getUsers().containsKey(user2Id))) {
Почему бы сразу не вызывать getUserById и не сохранить в переменные?

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Тут тоже можно сделать оптимальнее с сохранением результата userStorage.getUserById(user1Id)

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@RestController
Этой аннотации здесь не должно быть

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Validated
Это тоже сомнительная

2022-09-17 20:18 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> mostLikedFilms = new ArrayList<>();
Можно очень компактно написать с помощью стримов:
return filmStorage.viewAllFilms().stream()
				.sorted(new FilmLikesReversedComparator())
				.limit(count)
				.collect(Collectors.toList());

2022-09-17 22:05 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@RestController
А куда ее пихать? Slf4j для логов вроде нужна, а остальные нужно вынести на контроллер?

2022-09-17 22:06 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> mostLikedFilms = new ArrayList<>();
ну оно работает же. Я вот сейчас смотрю как раз про стримы

2022-09-17 22:09 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +        ApplicationContext context = SpringApplication.run(FilmorateApplication.class, args);
На StackOverflow нашел, по-моему по поводу прохождению юнит-тестов ...

2022-09-17 22:17 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> mostLikedFilms = new ArrayList<>();
Я стараюсь не использовать то, на что не на 100% понимаю :(

2022-09-18 08:50 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +        ApplicationContext context = SpringApplication.run(FilmorateApplication.class, args);
А какие-то тесты не проходили? Лучше разбираться в этом, на SO много шаманского

2022-09-18 08:52 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@RestController
Конкретно @restcontroller и @validated лишние

2022-09-18 08:52 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> mostLikedFilms = new ArrayList<>();
Поэтому комментарий начинается с "можно", а не "нужно"

2022-09-18 19:15 UTC, alexache approved these changes

2022-09-19 00:10 UTC, merged