Add database
dmmitr632/java-filmorate pull request #16
Opened 2022-11-30 10:01 UTC by dmmitr632

Пока еще лайки не работают, сейчас исправляю

2022-12-01 22:39 UTC, alexache requested changes

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            ArrayList<Genre> genres = this.getGenreForFilmByFilmId(film.getId());
Это не самый эффективный вариант с вызывами базы данных в цикле. В случае с mpa можно переписать select чтобы брались данные и из mpa таблицы, В случае жанров, нужно запросить все жанры для списка фильмов

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        findFilmByIdInDb(filmId);
Для чего это? Вроде бы объект фильма и так получен перед этим запросом

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        String query = "SELECT * FROM genres WHERE id IN (SELECT genre_id FROM films_genres WHERE id = ?)";
Какой-то не очень хороший запрос. Вложенный селект всегда вызывает вопрос, а здесь так и вовсе можно обойтись простым запросом по 2 таблицам: select * from genres g, films_genres fg where fg.genre_id = g.genre_id AND fg.Ffilm_id=?

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        String query = "SELECT * FROM mpa WHERE mpa.id IN(SELECT mpa_id FROM films WHERE id = ?)";
И это тоже не очень хороший запрос, к тому же и весь метод лишний, обычный селект для выбора фильма может возвращать информацию и по мпа рейтингу

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +                "SELECT * FROM genres WHERE id IN (SELECT genre_id FROM films_genres WHERE id = ?)";
Можно обойтись без вложенных селектов

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserDbStorage.java
> +        String query = "MERGE INTO users(id, email, login, name, birthday)" + " VALUES(?, ?, ?, ?, ?)";
Почему не update?

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserDbStorage.java
> +        findUserByIdInDb(user.getId());
Для чего 2 одинаковых метода?

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserDbStorage.java
> +        String query = ("SELECT * FROM users");
Для чего круглые скобки?

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserFriendsDbStorage.java
> +        String query = "SELECT * FROM users WHERE id IN (SELECT friend_id FROM users_friends WHERE id = ?)";
Лучше переписать на простой селект по 2 таблицам

2022-12-01 22:39 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserFriendsDbStorage.java
> +        String query = "SELECT *FROM users WHERE id IN(SELECT * FROM (SELECT friend_id FROM (" +
Вложенные селекты не самаялучшая идея: это легко перепишется на селект по 3 записям (2 раза на таблицу друзей по этим 2 юзерам и один раз на таблицу юзеров для общих друзей

2022-12-02 04:29 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        findFilmByIdInDb(film.getId());
Это проверка на то, что фильм с таким id уже существует в БД. Наверное, если MERGE заменить на UPDATE  она не нужна, сейчас попробую.

2022-12-02 04:32 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserDbStorage.java
> +        String query = ("SELECT * FROM users");
наверное, скопировал с вложенного SELECT и забыл удалить

2022-12-02 04:46 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            jdbcTemplate.update(queryAddGenreFilm, film.getId(), null);
раньше у меня без этого if-else выпадала ошибка, сейчас попробую разобраться

2022-12-02 05:19 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            stmt.setObject(3, film.getReleaseDate());
.setDate требует Date, нужно тогда писать stmt.setDate(3, Date.valueOf(film.getReleaseDate()))
Вот тут [https://stackoverflow.com/a/38809770/17120640](https://stackoverflow.com/a/38809770/17120640) , не разобрался до конца по какой причине, посоветовали именно setObject для Java 8 и позже.

2022-12-02 05:45 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        Mpa rating = this.getRating(film.getId());
Без нее ответ от сервера не включает имя рейтинга mpa name. Но это, наверное, не обязательно.
{
    "id": 1,
    "mpa": {
        "id": 1,
        "name": null //с этой строчкой будет "G"
    },
    "name": "nisi eiusmod",
    "description": "adipisicing",
    "releaseDate": "1967-03-25",
    "duration": 100,
    "rate": null,
    "genres": null,
    "mpaId": 1
}

2022-12-02 06:02 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            jdbcTemplate.update(queryAddGenreFilm, film.getId(), null);
Сейчас тоже вылетает. Если список genresWithoutDuplicates == null, то
List<Genre> genres = new ArrayList<>(film.getGenres());
падает с ошибкой nullpointerexception
Как и 
for (Genre genre : genresWithoutDuplicates)

2022-12-02 06:04 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            for (Genre genre : genresWithoutDuplicates) {
Можешь чуть поподробнее?

2022-12-02 06:12 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            jdbcTemplate.update(queryAddGenreFilm, film.getId(), null);
Вот [тут](https://stackoverflow.com/questions/27107072/adding-null-values-to-arraylist#comment125304479_27107189) пишут, что можно сделать  через Stream.of(null, "a").toList()
"List.of(...) will throw exception however Stream.of(null, "a").toList() works perfectly fine."

2022-12-02 06:29 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        findFilmByIdInDb(film.getId());
Не выходит. Если MERGE поменять на  "UPDATE films SET id =?, name = ?, description =? , release_date = ?, duration =? , rate =?, " +  "mpa_id = ?"; 
То валится на тесте film update genre и других.
Если оставить MERGE, но убрать проверку findFilmByIdInDb то на Film update unknown, Film get all, итп

2022-12-02 06:36 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        findFilmByIdInDb(film.getId());
findFilmByIdInDb() выбрасывает ошибку NotFoundException, если фильма с таким id не существует, что требуется в тестах

2022-12-02 06:40 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/UserDbStorage.java
> +        findUserByIdInDb(user.getId());
случайно оставил

2022-12-02 07:13 UTC, dmmitr632 commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        String query = "SELECT * FROM mpa WHERE mpa.id IN(SELECT mpa_id FROM films WHERE id = ?)";
SELECT по фильму не возвращает имя рейтинга же

2022-12-02 17:26 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        Mpa rating = this.getRating(film.getId());// unnecessary. adds mpa name to server response
Не очень понимаю зачем, во входном объекте для сохранения уже должен быть полноценный объект MPA

2022-12-02 17:26 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            jdbcTemplate.update(queryAddGenreFilm, film.getId(), null);
Для чего if я могку понять, а вот для чего update c null списком не понимаю

2022-12-02 17:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            for (Genre genre : genresWithoutDuplicates) {
`		jdbcTemplate.batchUpdate(
				queryAddGenreFilm,
				new BatchPreparedStatementSetter() {
					public void setValues(PreparedStatement ps, int i) throws SQLException {
						ps.setLong(1, film.getId());
						ps.setLong(2, genresWithoutDuplicates.get(i).getId());
					}

					public int getBatchSize() {
						return genresWithoutDuplicates.size();
					}
				});`

2022-12-02 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
>          for (Genre genre : genres) {
Удаление в цикле тоже плохо, почему не выполнить одну операцию DELETE FROM fils_genres where id =  ?
То есть удалить все жанры, связанные с этим фильмом

2022-12-02 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
>          List<Genre> genres = jdbcTemplate.query(queryGetGenresForFilm, new GenreMapper(), film.getId());
И эта операция в целом лишняя. Можно просто всегда безусловно удалять все жанры, связанные с данным фильмом, как я описал в комменте ниже

2022-12-02 17:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            ArrayList<Genre> genres = this.getGenreForFilmByFilmId(film.getId());
Этот комментарий еще валиден - запросы в цикле к базе не очень хорошо. В методе getRating у тебя на самом деле написан очень правильный запрос, который нужен для всех запросов фильмов и фильма по айди (не как отдельный вызов)

2022-12-02 17:42 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        String query = "SELECT * FROM mpa WHERE mpa.id IN(SELECT mpa_id FROM films WHERE id = ?)";
Это зависиит от того, как написать селект - вполне себе может именно с таким селектом, который у тебя теперь здесь

2022-12-03 21:38 UTC, alexache approved these changes

2022-12-03 21:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +                        .duration(duration).rate(rate).mpa(mpaRating).genres(new ArrayList<>(Collections.emptyList()))
Collections.emptyList()  тут лишнее - обычно это используют, если не хотят создавать новый объект списка

2022-12-03 21:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +            for (Genre genre : genresWithoutDuplicates) {
Это еще осталось на доработать к следующей итерации

2022-12-03 21:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        String queryAddGenreFilm = "INSERT INTO films_genres(id, genre_id) VALUES (?, ?)";
И здесь полное дублирование с методом addFilmGenre, зачем?

2022-12-03 21:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        String query = "SELECT * FROM films WHERE id = ?";
Пусть здесь тоже будет и MPA

2022-12-03 21:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/database/FilmDbStorage.java
> +        Mpa rating = this.getRating(film.getId());
Вызова этого метода уже лучше не иметь по аналогии с запросом по всем фильмам

2022-12-05 09:45 UTC, merged